name: CI Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CC: gcc-12
      CXX: g++-12
    steps:
      - uses: actions/checkout@v3
      - name: Install OpenMPI
        run: sudo apt-get install openmpi-bin libopenmpi-dev
      - name: Build and test
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../ -DMETALLDATA_BUILD_TESTS=ON
          make -j6
          make test
          cd ../tests
          sh run_test.sh